// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Api.Tests.PetServiceTests.Tests.Functional
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Pet Api Feature Tests")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("pet")]
    [global::NUnit.Framework.CategoryAttribute("functional")]
    public partial class PetApiFeatureTestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "pet",
                "functional"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "PetServiceTests/Tests/Functional", "Pet Api Feature Tests", "  In order to prevent known defects from reappearing\r\n  As an API consumer\r\n  I w" +
                "ant invalid and inconsistent pet API behavior to be rejected correctly", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "PetTests.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("PetServiceTests/Tests/Functional/PetTests.feature.ndjson", 13);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet with string id should be rejected without server error")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("string_pet_id_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithStringIdShouldBeRejectedWithoutServerError()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "string_pet_id_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet with string id should be rejected without server error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
    await testRunner.GivenAsync("I have the pet with invalid string-type Id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
    await testRunner.WhenAsync("I create the pet with invalid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
    await testRunner.ThenAsync("the response status code should be \'500\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet with an out of range numeric id should be rejected without server " +
            "error")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("oversized_pet_id_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithAnOutOfRangeNumericIdShouldBeRejectedWithoutServerError()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "oversized_pet_id_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet with an out of range numeric id should be rejected without server " +
                    "error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("I have a pet with an id longer than long", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("I create the pet with invalid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("the response status code should be \'500\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet with string category id should be rejected without server error")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("string_category_id_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithStringCategoryIdShouldBeRejectedWithoutServerError()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "string_category_id_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet with string category id should be rejected without server error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 44
    await testRunner.GivenAsync("I have the pet with invalid string-type category Id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.WhenAsync("I create the pet with invalid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
    await testRunner.ThenAsync("the response status code should be \'500\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet with out of range category id should be rejected without server er" +
            "ror")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("oversized_category_id_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithOutOfRangeCategoryIdShouldBeRejectedWithoutServerError()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "oversized_category_id_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet with out of range category id should be rejected without server er" +
                    "ror", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
    await testRunner.GivenAsync("I have the pet with category Id longer than long", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
    await testRunner.WhenAsync("I create the pet with invalid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.ThenAsync("the response status code should be \'500\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet with string tag id should be rejected without server error")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("string_tag_id_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithStringTagIdShouldBeRejectedWithoutServerError()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "string_tag_id_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet with string tag id should be rejected without server error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 71
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
    await testRunner.GivenAsync("I have the pet with invalid string-type tag Id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
    await testRunner.WhenAsync("I create the pet with invalid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
    await testRunner.ThenAsync("the response status code should be \'500\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet with out of range tag id should be rejected without server error")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("oversized_tag_id_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithOutOfRangeTagIdShouldBeRejectedWithoutServerError()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "oversized_tag_id_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet with out of range tag id should be rejected without server error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 85
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 86
    await testRunner.GivenAsync("I have the pet with tag Id longer than long", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 87
    await testRunner.WhenAsync("I create the pet with invalid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.ThenAsync("the response status code should be \'500\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Retrieving a pet with a non numeric id should not leak implementation details")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("get_invalid_raw_id_exception_leak")]
        public async global::System.Threading.Tasks.Task RetrievingAPetWithANonNumericIdShouldNotLeakImplementationDetails()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "get_invalid_raw_id_exception_leak"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retrieving a pet with a non numeric id should not leak implementation details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 98
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 99
    await testRunner.WhenAsync("I try to retrieve the pet by id \'*\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
    await testRunner.ThenAsync("the response status code should be \'404\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Deleting a pet with a non numeric id should not leak implementation details")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("delete_invalid_raw_id_exception_leak")]
        public async global::System.Threading.Tasks.Task DeletingAPetWithANonNumericIdShouldNotLeakImplementationDetails()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "delete_invalid_raw_id_exception_leak"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deleting a pet with a non numeric id should not leak implementation details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 110
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 111
    await testRunner.WhenAsync("I delete the pet by id \'fluff\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 112
    await testRunner.ThenAsync("the response status code should be \'404\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet without name should be rejected")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("missing_name_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithoutNameShouldBeRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "missing_name_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet without name should be rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 123
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 124
    await testRunner.GivenAsync("I have a pet with no name", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 125
    await testRunner.WhenAsync("I create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 126
    await testRunner.ThenAsync("the response status code should be \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet without category should be rejected")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("missing_category_validation")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithoutCategoryShouldBeRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "missing_category_validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet without category should be rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 137
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 138
    await testRunner.GivenAsync("I have a pet with no category", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 139
    await testRunner.WhenAsync("I create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
    await testRunner.ThenAsync("the response status code should be \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Creating a pet with duplicate id should be rejected")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        [global::NUnit.Framework.CategoryAttribute("duplicate_id_handling")]
        public async global::System.Threading.Tasks.Task CreatingAPetWithDuplicateIdShouldBeRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "bug",
                    "duplicate_id_handling"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating a pet with duplicate id should be rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 152
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table1.AddRow(new string[] {
                            "id",
                            "5452245"});
                table1.AddRow(new string[] {
                            "name",
                            "Fluffy"});
                table1.AddRow(new string[] {
                            "category",
                            "Cats"});
                table1.AddRow(new string[] {
                            "tag",
                            "Friendly"});
                table1.AddRow(new string[] {
                            "photoUrl",
                            "https://example.com/a"});
                table1.AddRow(new string[] {
                            "status",
                            "sold"});
#line 153
    await testRunner.GivenAsync("I have a pet with", ((string)(null)), table1, "Given ");
#line hidden
#line 161
    await testRunner.AndAsync("I create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
    await testRunner.AndAsync("the response status code should be \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table2.AddRow(new string[] {
                            "id",
                            "5452245"});
                table2.AddRow(new string[] {
                            "name",
                            "Fluffy"});
                table2.AddRow(new string[] {
                            "category",
                            "Cats"});
                table2.AddRow(new string[] {
                            "tag",
                            "Friendly"});
                table2.AddRow(new string[] {
                            "photoUrl",
                            "https://example.com/a"});
                table2.AddRow(new string[] {
                            "status",
                            "sold"});
#line 164
    await testRunner.AndAsync("I have a pet with", ((string)(null)), table2, "And ");
#line hidden
#line 172
    await testRunner.WhenAsync("I create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 173
    await testRunner.ThenAsync("the response status code should be \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
